# data
data:
  timit:
    path: datasets/timit
    n_classes: 462

# model
model:
  type: cnn
  pretrain: null

# sound
sample_rate: 16000
chunk_len_ratio: 0.2
chunk_shift_ratio: 0.01

# optimization
lr: 0.001
batch_size: 128
n_epochs: 66666 #1500

# other
device: 'cuda:0'
verbose_every: 400
save_path: 'src/model/'
use_wandb: false
